let userName = prompt('WHAT IS YOUR NAME?')
let userQuest = prompt ('What is your quest?')
let userFavoriteColor = prompt('What is your favorite color?')
let userAge = prompt ('What is your age?')
console.log (userName)